# Inspired by https://github.com/f3d-app/f3d-superbuild/blob/main/projects/openusd.cmake

superbuild_add_project(openusd
  BUILD_SHARED_LIBS_INDEPENDENT
  LICENSE_FILES
    LICENSE.txt
  DEPENDS tbb
  CMAKE_ARGS
    -DPXR_BUILD_EXAMPLES:BOOL=OFF
    -DPXR_BUILD_IMAGING:BOOL=OFF
    -DPXR_BUILD_MONOLITHIC:BOOL=ON
    -DPXR_BUILD_TESTS:BOOL=OFF
    -DPXR_BUILD_TUTORIALS:BOOL=OFF
    -DPXR_BUILD_USD_TOOLS:BOOL=OFF
    -DPXR_ENABLE_GL_SUPPORT:BOOL=OFF
    -DPXR_ENABLE_PRECOMPILED_HEADERS:BOOL=OFF
    -DPXR_ENABLE_PYTHON_SUPPORT:BOOL=OFF
    -DPXR_INSTALL_LOCATION:STRING=../lib/usd
)
