# Lines can be generated by doing:
#
#   sha256sum $files | awk '{ print "set(\"" $2 "_hash\" " $1 ")" }' >> $thisfile

set("6.9.0-0-202503301022icu-linux-Rhel8.6-x86_64.7z_hash" 692439c95e3c40a851c57a7132dc66c244e2a1de85f8e576b53528ed70a5ef01)
set("6.9.0-0-202503301022qt5compat-Linux-RHEL_8_10-GCC-Linux-RHEL_8_10-X86_64.7z_hash" f33dd2d843b316833fd37f8e64138adcdf3761384933a3c897aa1dc51a3da7ff)
set("6.9.0-0-202503301022qtbase-Linux-RHEL_8_10-GCC-Linux-RHEL_8_10-X86_64.7z_hash" c6f2bb9b2384cb9633eb2923e47de297555002ee4fac4b678be9c0d7d2d1a999)
set("6.9.0-0-202503301022qtmultimedia-Linux-RHEL_8_10-GCC-Linux-RHEL_8_10-X86_64.7z_hash" b441cd14c9ee77c15103bd5ad736700b830bda3087bbe00d8579ad45ce16e150)
set("6.9.0-0-202503301022qtsvg-Linux-RHEL_8_10-GCC-Linux-RHEL_8_10-X86_64.7z_hash" 522ec21a90f274cf2bc03fed37c81065cd81e736c8f85e51c293f67af0d42db1)
set("6.9.0-0-202503301022qttools-Linux-RHEL_8_10-GCC-Linux-RHEL_8_10-X86_64.7z_hash" 1a70be6042a26bf19fd279d0df7b8b7fc0edc59e0c89f3ac2e54f530653ac56e)

set("6.9.0-0-202503301021qt5compat-MacOS-MacOS_14-Clang-MacOS-MacOS_14-X86_64-ARM64.7z_hash" 88b756ab89ec2b2c25f16d61fdbc1f16f7779a4d569f2d46be5683988b91d528)
set("6.9.0-0-202503301021qtbase-MacOS-MacOS_14-Clang-MacOS-MacOS_14-X86_64-ARM64.7z_hash" 373d845a3da6d0c35ff09a07a168567b356766e7269401a10e865f4e88dddca3)
set("6.9.0-0-202503301021qtmultimedia-MacOS-MacOS_14-Clang-MacOS-MacOS_14-X86_64-ARM64.7z_hash" a0150f14fe999cad5b804f1c6f9d1f3c65ab6fa6e112b55cc30807a9257f9e6d)
set("6.9.0-0-202503301021qtsvg-MacOS-MacOS_14-Clang-MacOS-MacOS_14-X86_64-ARM64.7z_hash" 852e96ed4c77d69d43ac6379005ba0dafbc798ee1c7f939d8847ce7cc653e100)
set("6.9.0-0-202503301021qttools-MacOS-MacOS_14-Clang-MacOS-MacOS_14-X86_64-ARM64.7z_hash" a5aab7c901f72ac3a18ff29f96f831ccea747cf88012cd208a039b2287aeb29b)

set("6.9.0-0-202503301022d3dcompiler_47-x64.7z_hash" 1740824d03f27e85e553a8fc8076c7f321252143844318b6b3b9662ac6f97582)
set("6.9.0-0-202503301022opengl32sw-64-mesa_11_2_2-signed_sha256.7z_hash" c9dc9f36b4ffbabdc6166e57ff137c51d0846ace38dfe20b02a7db2ec76bfc31)
set("6.9.0-0-202503301022qt5compat-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z_hash" 86d3737cff83ce06420869becf90cc1f9d5c882e5d6a4bbbe011e0f3cf04435c)
set("6.9.0-0-202503301022qtbase-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z_hash" 5a2db7a2cabb0ce09171d5600a8d420d0395d159389d62a1edbc58a4f3237537)
set("6.9.0-0-202503301022qtmultimedia-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z_hash" 675dd43692cdd73fb22237115be452f237492b8fcb682e04e14ce387e304b9d3)
set("6.9.0-0-202503301022qtsvg-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z_hash" 99076dbc1ddc97b23d76b6658b3b6613850db316d388e59c1d8563ddc2f1521b)
set("6.9.0-0-202503301022qttools-Windows-Windows_11_23H2-MSVC2022-Windows-Windows_11_23H2-X86_64.7z_hash" 5f5749bde8fe8e931cfd51a4dcfc5439c090489bc9b79f34483edaa1e77cbb35)
